use_frameworks!

target 'PR2StudioSwift3_Example' do
  pod 'PR2StudioSwift3', :path => '../'

  target 'PR2StudioSwift3_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
